Render Audio Player if Tool Result resource mime type is audio.
modelcontextprotocol/inspector pull request #99
Opened 2024-12-01 10:29 UTC by evalstate

Show the browser audio player if resource mime type is audio.

## Motivation and Context
Makes testing audio tool results integration easier.

## How Has This Been Tested?
This has been tested with an MCP Server calling Parler/TTS.

```
...
      const audioBase64 = await generateSpeech(text);
      return {
        content: [{
          type: "resource",
          resource: {
            uri: "audio:///" + crypto.randomUUID(),
            mimeType: "audio/wav",
            blob: audioBase64
          }
        }]
      };
    }
...

async function generateSpeech(text: string): Promise<string> {
  const client = await Client.connect("parler-tts/parler_tts");
  const result = await client.predict("/gen_tts", {
    text,
    description: "Laura's voice is monotone yet slightly fast in delivery, with a very close recording that almost has no background noise.",
    use_large: false
  });
  
  // Fetch the audio file
  const response = await fetch(result.data[0].url);
  const arrayBuffer = await response.arrayBuffer();
  
  // Convert to base64
  const base64 = Buffer.from(arrayBuffer).toString('base64');
  
  return base64;
}

```

## Breaking Changes
No - but the Client Reference Implementation (Claude Desktop does not support Audio content).

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update

## Checklist

- [X] I have read the [MCP Documentation](https://modelcontextprotocol.io)
- [X] My code follows the repository's style guidelines
- [X] New and existing tests pass locally
- [X] I have added appropriate error handling
- [X] I have added or updated documentation as needed

2024-12-01 16:12 UTC, ashwin-ant requested changes
Thank you! Just one small suggestion.

2024-12-01 16:12 UTC, ashwin-ant commented on client/src/components/ToolsTab.tsx
> +export type ExtendedCallToolResult = z.infer<typeof ExtendedCallToolResultSchema>;
nit: no real need to export these

If you want, you could move these into a new file at `src/lib/toolTypes.ts` the same way we have `src/lib/notificationTypes.ts`.

2024-12-01 16:40 UTC, evalstate commented on client/src/components/ToolsTab.tsx
> +export type ExtendedCallToolResult = z.infer<typeof ExtendedCallToolResultSchema>;
Thanks @ashwin-ant  - I hadn't meant to put the second commit on this branch 😳, so have removed it.

The first commit (the intended PR) is to render Audio.

The second (now removed, unintended commit) was to test a potential change to the Spec (https://github.com/modelcontextprotocol/specification/discussions/88).

2024-12-03 23:28 UTC, ashwin-ant commented
Hey @evalstate, apologies for the delay here. After some consideration, we'd like to avoid having the inspector showcase any features that aren't in the official spec. So this particular PR will need to wait until the spec discussion you started gets to a resolution.

2024-12-03 23:34 UTC, evalstate commented
Hi Ashwin -

This PR renders the audio component if the mime type of the Resource is audio (so in-spec). It's very convenient for testing.

The reverted commit handled the change to the Schema - and was accidentally committed to the branch. Ideally changes to the spec could be coordinated with updates to SDK and Inspector for testing. I fat-fingered this one - hence the delete of that commit .

Best.

2025-01-28 07:15 UTC, jerome3o-anthropic approved these changes
looks good to me, thank you for this (sorry taking a long time to get to this!)

I don't have state on the previous iterations, but the diff looks good to me as is

2025-01-28 07:22 UTC, jerome3o-anthropic commented
I think you just need to just run `npx prettier --write .` on thisto have it merged

2025-01-28 08:30 UTC, evalstate commented
Done!

2025-02-02 23:12 UTC, jerome3o-anthropic approved these changes
Awesome - thank you for that

2025-02-02 23:28 UTC, jerome3o-anthropic approved these changes
It looks like some other additional changes were added in [this commit](https://github.com/modelcontextprotocol/inspector/pull/99/commits/a87bd17f51e1f19635fd0b1a9be514a4b2032203) that I hadn't reviewed, I think this is what the prior conversation in the PR was about.

I've checked out the commit I approved locally and ran the linter + commited, so I'm going to merge this as is and we can work on the new types next / spec expansion next

2025-02-02 23:28 UTC, merged

2025-02-03 09:21 UTC, evalstate commented
thanks @jerome3o-anthropic - sorry about that, re-adding those additional changes wasn't intentional. is there a view on how to manage new protocol versions gracefully?